name: Tests

on:
  workflow_dispatch:
  pull_request: 
    types: [ opened, synchronize, reopened ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start Vite server
        run: npm run dev &
        env:
          CI: true

      - name: Wait for Vite server
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5173/retroleaderboards/; then
              echo "Vite server is up!"
              break
            fi
            echo "Waiting for Vite server..."
            sleep 2
          done

      - name: Set environment variables
        run: echo "VITE_ENCRYPTION_KEY=1234567890" >> $GITHUB_ENV

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
