name: Tests

on:
  workflow_dispatch:
  pull_request: 
    types: [ opened, synchronize, reopened ]

jobs:
  cypress_run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev:expose
          wait-on: 'http://localhost:5173/retroleaderboards'
          env: VITE_ENCRYPTION_KEY=1234567890_KEY

    #   - name: Install dependencies
    #     run: npm install

    #   - name: Start Vite server
    #     run: npm run dev &
    #     env:
    #       VITE_ENCRYPTION_KEY: 1234567890_KEY

    #   - name: Wait for Vite server
    #     run: |
    #       for i in {1..10}; do
    #         if curl -s http://localhost:5173/retroleaderboards/; then
    #           echo "Vite server is up!"
    #           break
    #         fi
    #         echo "Waiting for Vite server..."
    #         sleep 2
    #       done

    #   - name: Run Cypress tests
    #     run: npm run cy:run
